from typing import Any, Iterator


class SSEClient:
    def __init__(self, url: str, session: Any = ..., **kwargs: Any) -> None: ...
    def __iter__(self) -> Iterator[Any]: ...
    def __next__(self) -> Any: ...
    def _connect(self) -> None: ...
    @property
    def resp(self) -> Any: ...
    running: bool
    retry: int